### ISSUE TITLE
when defaultQueryString contain point atlasPath will error

### ISSUE THREAD

**Issue by wwepenguin** [pixijs/spine#236]
https://github.com/pixijs/pixi-spine/blob/f276b49c878a1e5ce0feaa1e763d6a531a967a74/src/loaders.ts#L39

if my loader queryString contain point like  , loader.defaultQuery = '1.0'

this line substring index 0 to lastIndexOf point  file path will error

can substr to '.json'? or remove queryString before that?

sorry for my poor english..

**Comment by wwepenguin** [comment]
@ivanpopelyshev  thank for your fast reply ,
 
and i fix it like

 let atlasPath = resource.url.substr(0, resource.url.lastIndexOf('.json')) + metadataAtlasSuffix; 

 in my project to fix this problem

**Comment by ivanpopelyshev** [comment]
Thank you! I'll add extra "if" there with your case.,
