### ISSUE TITLE
Light & Dark tinting? Doesn't seem to work...

### ISSUE THREAD

**Issue by st3v0** [pixijs/spine#255]
It looks like basic light tinting is working however dark tinting doesn't. [pixi-heaven](https://github.com/gameofbombs/pixi-heaven) has attempted to solve the issue and has even managed to push some [changes](https://github.com/pixijs/pixi-spine/commit/5e62232746c2261f68973f2aa30c7f30c5bc2636#diff-8add1b624d5642b5987307c412b08a43) into pixi-spine however it's not quite working since tints don't work on meshes.

Is there any plans to implement this functionality into pixi-spine since it's very useful to have?

**Comment by ivanpopelyshev** [comment]
It should work if you use pixi-spine with pixi-heaven. Unfortunately, its not possible with vanilla pixi shaders.
