### ISSUE TITLE
How to display drawDebug

### ISSUE THREAD

**Issue by sbfkcel** [pixijs/spine#324]
Cannot find `drawRegionAttachments`,` drawClipping`, `drawBones`,` drawMeshHull`, `drawMeshTriangles` options
----
Is this series of options not available in pixi-spine?

**Comment by ivanpopelyshev** [comment]
Nope, you are free to make PR to introduce them :) Just fill up a Graphics element with stuff. If they exist in original spine-ts, you can copy part of code from here: https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-ts

**Comment by sbfkcel** [comment]
It is recommended to add, or in the form of extension.

**Comment by ivanpopelyshev** [comment]
Whatever will be easy for you. Here's stub for drawMesh: https://codesandbox.io/s/laughing-robinson-oowcm 

Also, good idea is to call redraw on every update(), you can hack it easily from outside:

```
const oldUpdate = Spine.prototype.update;
Spine.prototype.update = function( dt) { oldUpdate.call(this, dt); this.updateMyDebugGraphics(); }
Spine.prototype.updateMyDebugGraphics = function() { ... }
```

**Comment by sbfkcel** [comment]
👍🏻Thank you.

**Comment by sbfkcel** [comment]
I had to reopen the theme. I find a lot of data is not available. For example: `bone.a`,` bone.c`

**Comment by ivanpopelyshev** [comment]
In pixi-spine implementation all matrix data is in `bone.matrix`. Also, `b` and `c` are swapped because Spine is only software that uses 

```
a b tx
c d ty
```

everyone else, and pixi too uses

```
a c tx
b d ty
```

so compared to spine sources, our `b` and `c` are swapped.

**Comment by sbfkcel** [comment]
Ok i try to write a debug plugin

If you have any questions, please ask

**Comment by sbfkcel** [comment]
On which object is `vertices`?

The computeWorldVertices method is slightly different from the original spine.

**Comment by ivanpopelyshev** [comment]
Vertices array is created when we create `PIXI.SimpleMesh`: https://github.com/pixijs/pixi-spine/blob/master/src/Spine.ts#L564

That's how we update them: https://github.com/pixijs/pixi-spine/blob/master/src/Spine.ts#L359

**Comment by sbfkcel** [comment]
I am willing to do my best to help others ^ _ ^.

----
I found that the slot only has `currentMesh`,` currentMesh.vertices` when the constructor is `MeshAttachment`?

Is there no `vertices` attribute in other cases?

**Comment by sbfkcel** [comment]
When the `slot.attachment` constructor is` PIXI.spine.core.RegionAttachment`, its `vertices` does not exist.

```javascript
for(let i=0,len=slots.length; i<len; i++){
    let slot = slots[i],
        attachment = slot.getAttachment();
    if (attachment instanceof PIXI.spine.core.RegionAttachment) {
        console.log(slot.vertices,attachment.vertices);  
    }
};
```

**Comment by ivanpopelyshev** [comment]
Yes, it doesn't because we really don't need it, all computations are done in `PIXI.Sprite`: https://github.com/pixijs/pixi-spine/blob/master/src/Spine.ts#L468 . Local spine coords aren't calculated , but global ones are inside `currentSprite.vertexData`, they only appear there after `currentSprite.calculateVertices()` which is called inside sprite render method.

I don't know what to recommend there :( You can manually call that computeWorldVertices and give temp array that you copy and pass to graphics drawPolygon.

**Comment by sbfkcel** [comment]
oh,So easy

**Comment by ivanpopelyshev** [comment]
If computeWorldVertices doesnt produce result you need, it ma be because right now we use `PIXI.Texture` fields instead of region, so it can be a problem. I commented out `updateRegion` or `region.updateUvs()` or something like that, i dont remember :)

**Comment by sbfkcel** [comment]
The current result is indeed not a region

```
Float32Array(8) [-28.063657760620117, -212.8229522705078, -28.063657760620117, -212.8229522705078, -28.063657760620117, -212.8229522705078, -28.063657760620117, -212.8229522705078]
```

**Comment by ivanpopelyshev** [comment]
here it is:

https://github.com/pixijs/pixi-spine/blob/1f06f5c91554aeb336e1df6553af4c82dea9449e/src/core/SkeletonJson.ts#L339

You can call `updateOffset()` on that region.

**Comment by sbfkcel** [comment]
Has been written

https://github.com/sbfkcel/pixi-spine-debug

**Comment by ivanpopelyshev** [comment]
Ok, added to https://github.com/pixijs/pixi.js/wiki/v5-Resources temporarily. I will think how to integrate this in main pixi-spine package.

Now that it actually works, we can think those architecture-related things.

Usually I don't add N new fields, I just make a component, like `spineObj.debug = mySpineDebug` and call it from `update`:

```
let debug = new SpineDebug();
debug .drawDebug = true;
debug .drawBones = true;

...

spine1.debug = debug;
spine2.debug = debug;
```

and spine object calls it:
```js
if (this.debug) {
    this.debug.update(this);
}
```

That way it'll be possible to share that component across many spine objects.
I'm not asking you to change the plugin right now, lets discuss it. What do you think about my approach?

**Comment by ivanpopelyshev** [comment]
If you make a screenshot how it looks, I can add it to https://github.com/pixijs/pixi-spine/blob/master/README.md

**Comment by sbfkcel** [comment]
Good proposal.
However, I think it is necessary to separate multiple fields.

-Enabling all edge drawing information will be too much, which is not good for debugging
-In most cases, only some spine elements can enable some edge information.
-However, it is a good choice to perform hierarchical debugging

```javascript
let debug1 = new SpineDebug({
     draw:['bones','paths,...],
     list:[spine1,spine2,...]
});
debug1.run();
```

**Comment by ivanpopelyshev** [comment]
Oh, yes, that's a good one :)

**Comment by sbfkcel** [comment]
demo

https://sbfkcel.github.io/pixi-spine-debug/

**Comment by djmisterjon** [comment]
nice jobs guys this look very awesome for debug.
I think it missing a **draw events names**.
