### ISSUE TITLE
Setting animation nulls slot.attachment which breaks when attempting hackTextureBySlotIndex

### ISSUE THREAD

**Issue by st3v0** [pixijs/spine#331]
We have an issue where setting an animation causes the slot attachment to `null`. This happens during the first update call right after:

https://github.com/pixijs/pixi-spine/blob/0e0431a81b2a061a872730b2cd6f7fa83413763b/src/Spine.ts#L245

To clarify, the slot has an attachment with a region when the spine is initialized, however after the animation is set and the `state.apply` called the attachment is null.

We then try to run `hackTextureBySlotIndex()` but it fails here of course because you can't access `region` of `null`.

https://github.com/pixijs/pixi-spine/blob/0e0431a81b2a061a872730b2cd6f7fa83413763b/src/Spine.ts#L624

Should slots be losing refs to their attachments, what do we do in situations like this where we want to swap out a texture but the slot has lost the ref to it?

**Comment by st3v0** [comment]
To provide more context this is in relation to #320

We're loading 2 Spine assets, one being a much lower res (and thus smaller file size). The small low res is loaded first, then later on the second spine is load and should seamlessly swap out the initial spine.

So either I have to sync the animation data some how or i just swap the underlying texture data of the first spine, the latter being what we choose to implement.

**Comment by ivanpopelyshev** [comment]
>  i just swap the underlying texture data of the first spine,

You can iterate through all textures of atlas, set different baseTexture. You don't even need to adjust the frame and UV's , they are the same.

**Comment by st3v0** [comment]
Here's a example for you:  

[![Edit pixi-spine issue #331](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pixi5-addchild-bug-t3uo5?fontsize=14&hidenavigation=1&theme=dark)

For more context, I'll try an explain what's happening here. There are 2 spineboy assets being loaded, 1 hi-res with a highlight yellow torso, and 1 low-res with a highlighted pick torso (an green body). We've added an animation to them called `na`. This disables all but the torso slot. Both spines contain identical attachments however the atlas region information will be slightly different because the texture was packed differently.

The first time you click the stage it will attempt to swap all attachments of all slots. You will see the yellow torso turn pink and the rest of spineboy will appear and start walking. However at this stage all of spineboy should be green (which it's not). This is because all of the first spine slots should have been switched with the second green spineboy. 

If you click the stage a second time while his walking you will see that the rest of the slots get swapped. You should now be seeing green spineboy with a pink torso.

I've added a log to detail the slots which don't get swapped.

**Comment by ivanpopelyshev** [comment]
Hey! 

I forgot about that issue. Do you wstill need it?

**Comment by st3v0** [comment]
This can be closed. We solved the issue by simply duplicating the spine and syncing across all the timelines, attachments and listeners. Then just swapping out the old spine with the new one.
