### ISSUE TITLE
[imagname]2.png Path Issue

### ISSUE THREAD

**Issue by frankmcpolin** [pixijs/spine#337]
Basically, I have an exported animation (in both '1' and '0.5' res) that turned out to be so big that the full sized export has created and packed a second png. The file structure looks like this:

/export
- wild_hades.json
- wild_poseidon.json
- wild_zeus.json
- /1
-- wilds.atlas
-- wilds.png
-- wilds2.png
- /0.5
-- wilds.atlas
-- wilds.png

I am loading these into the pixi-spine loader v2.1.8 - Spine version is v3.8.94.

When loading, it seems to load wilds.png ok, but fails to load wilds2.png. On inspection in the network tab, it would appear as though wilds.png is the correct path (ie including all the subfolders) but wilds2.png is just plain old wilds2.png (ie root url), and so understandably is failing.

Posted to the Esoteric form, and suggestion was...

It looks like a pixi-spine bug, somewhere in here:

https://github.com/pixijs/pixi-spine/blob/master/src/core/TextureAtlas.ts

Where it loads the atlas page texture, it needs to look for the **second** image (or maybe any number of multiple images) in the same folder of the atlas file.

**Comment by frankmcpolin** [comment]
Hello.

This is still an issue in pixi-spine 2.1.10 and is now happening in a different project.

Am I really the only person who has an export requiring 2 pngs?

Please post if you have experienced the same and whether you found a solution!

Thanks

**Comment by ivanpopelyshev** [comment]
Hi! Ii dont know how did i miss this thing.

First let me tell you how pixi deals with multiple resolutions: you can use `@0.5x` or `@.5x` suffix , and one of my plugins supports that:
https://github.com/pixijs/pixi-compressed-textures/tree/master/src

In future this will be moved to special URL-resolver thingy that exists in resource-loader v4 , which pixi doesnt use yet.

As for second file problem, well, you have to debug it. Really. I dont have that setup, i dont even use spine, i help people to fix problems based on their case and i dont have demo that has two images. In theory, it should work. I n practice, there's always something wrong with loader or atlas. So, you have to debug it yourself and tell me what to change in it, or you can give me full demo and then i'll debug it.

**Comment by frankmcpolin** [comment]
Thanks @ivanpopelyshev - Spine itself exports like the above and so I think the pixi-spine loader expects it in this way. It do think the issue is that the exporter generates a myImageName2.png if it can't fit it onto one sheet and the pixi-spine plugin for some reason doesn't even try to look for it!

I will take a look and see if I can debug it and let you know if I find the problem. Thanks.

**Comment by frankmcpolin** [comment]
Hi @ivanpopelyshev - I almost forgot all about this as the workaround is just to have the designers go back and reduce the size of everything until it only exports one png, but it is still a bit of a drag for them plus it means we often have to compromise on what we can do, so please find attached a project that exhibits this behaviour.

Thanks!
[background.zip](https://github.com/pixijs/spine/files/9333306/background.zip)

**Comment by ivanpopelyshev** [comment]
Oh, now i understand the issue, i'll check it )

**Comment by frankmcpolin** [comment]
Closing this as realised I was being a complete noob and simply not adding the additional exported png references to the loader... Sorry @ivanpopelyshev !!!
