### ISSUE TITLE
Spine versioning issues

### ISSUE THREAD

**Issue by st3v0** [pixijs/spine#369]
Hi,

Regarding the many different version of pixi-spine. I understand that for each major version of pixi you may have to create a fork of pixi-spine which is compatible with it due to API changes. Is it possible however to create a lib which is compatible with all versions of the spine engine, ie 3.5, 3.6, 3.7, 3.8 & 4.0.

The spine skeleton json has for a while now detailed the spine engine version it was built with. You could version your skeleton & atlas parsers based on the skeleton engine version in the json. Of course this would require you to first read the json version before parsing it.

This would mean when we bump our pixi-spine version to the latest we wouldn't have to go back and recompile all our old spine assets at the latest engine version. This is starting to become a large problem for us, so much that we've decided to lock off at 3.7, as the task for upgrading our existing catalog will take too long.

I'm certain there's a lot more to this story that i'm missing. There's probably some big functional or API differences between 3.7 & 3.8 that i'm not aware of. However with the upcoming release of pixi v6 and spine v4, this issue will start to become a bigger problem.

OR, Perhaps an intermediate (nasty) solution could be created where it's a single library coupled to a pixi version but containing all the different spine engine implementation versions. Then when we load the spine we check the skeleton version and exe `new PIXI.spine.Spine37(...)` or `new PIXI.spine.3_8.Spine(...)`, etc

I welcome your feedback.

**Comment by ivanpopelyshev** [comment]
Hello!

Yes, its pain. Currently we have special function that informs user in console that model format is for different version of spine.

I honestly dont know what to do with this thing except maybe different npm tags. Of course I will support both 3.7 and 3.8 for v6.

**Comment by st3v0** [comment]
For anyone else who has encountered this problem, we've created a gnarly hack for the time being which involves aliasing the dependencies, namespace rerouting with a spine wrapper.

### What we did

#### package.json
Here we include both pixi-v5, 3.7 & 3.8 spine engine versions.
```json
"dependencies": {
    "pixi-spine37": "npm:pixi-spine@2.0.5",
    "pixi-spine38": "npm:pixi-spine@2.1.11"
}
```

#### main.js
Then in our libraries main.js we have to work a little magic, like so;
```javascript
import * as PIXI from 'pixi.js';
window.PIXI = PIXI;

// XXX: This require returns a blank object and not the pixi-spine namespace. Instead the act of requiring it will register the
// PIXI.spine namespace. This is how we work around that issue.
require('pixi-spine37');
const spine37 = PIXI.spine;

// To be on the safe side we will de-ref the global pixi spine pointer.
PIXI.spine = null;

require('pixi-spine38');
const spine38 = PIXI.spine;

PIXI.spine = null;
PIXI.spine37 = spine37;
PIXI.spine38 = spine38;
```

#### spine.js
We have our own Spine class wrapper which encapsulates the pixi spine class. I can't paste it here exactly however in it there's a `createSpine()` method which returns the constructed spine. Here is that method in a nutshell;

```javascript
const ns = semver.satisfies(semver.coerce(spineData.version), '>3.7.x') ? Pixi.spine38 : Pixi.spine37;
const spine = new ns.Spine(spineData);
```

Before you create the skeleton data you will need to ensure you use the correct parser. We've achieved this by preloading the skeleton json and inspecting the spine version within it using `skeletonJson.skeleton.spine`. Once you have the correct spine namespace you can then;

```javascript
const spineJsonParser = new ns.core.SkeletonJson(spineAtlasLoader);
const spineData = spineJsonParser.readSkeletonData(skeletonJson);
```

### Last Words

This now means any project we have can have a mixture of both 3.7 & 3.8 spine assets. It's not pretty, It will double the size of the included pixi-spine dependency because you're now including 2 different implementations in your build. However it works and for any extra KB overhead it's worth it, because now we don't have to re-export all our spines when a new spine engine is released and the artist want to use the latest & greatest version.


**Important Note:** The upcoming spine engine v4 is a major version bump and most likely will come with breaking API changes. Our implementation might be able to cope with this since we're encapsulating the pixi-spine implementation with our own class. However this will only bend so far before it breaks.

**Comment by ivanpopelyshev** [comment]
Yeah, and we'll need v4 too, ahahahahahahaha

**Comment by ivanpopelyshev** [comment]
Actually , very good idea to spawn npm `pixi-spine-37`, `pixi-spine-38` and pixi-spine`-40`

**Comment by st3v0** [comment]
The other issue of course is heaven. We managed to get that working sort of by doing something similar. However it would be nice if two-tone tinting was in the pixi-spine core. Maybe a setting flag to enable it or something. I only argue this since it's a feature which spine already has built in, and I can't figure out why it would be left as a separate project, when it's already a built-in feature.

**Comment by ivanpopelyshev** [comment]
Yes, that's also good idea, into the core it will go.

**Comment by NathanSweet** [comment]
FWIW, Spine's workflow is to re-export your JSON/binary skeleton data files when updating major or minor versions:
http://esotericsoftware.com/spine-versioning#Synchronizing-versions
It is done this way to keep the runtimes and the data lean. The runtimes do not need to make sense of old data.

The Spine project files are like the source code and the JSON or binary data are like the compiled binary. When the runtimes are updated, you need new binaries.

I understand this can be an inconvenience, but with a little effort a script can be written to re-export everything in one go. That is also generally better when integrated into an app's build system, so changes to Spine project files are not missed.

**Comment by ivanpopelyshev** [comment]
Too late, i almost completed pixi-spine for v6 that supports everything :) you will be able to add/remove whatever model versions you need

**Comment by NathanSweet** [comment]
That's cool too! I just wanted to give the official stance.

BTW, a user [just asked](http://esotericsoftware.com/forum/Pixi-JS-Compatibility-with-Spine-V4-15773) about pixi-spine supporting Spine 4.0.

**Comment by ivanpopelyshev** [comment]
Tell him im doing it. Only for v6.

**Comment by ivanpopelyshev** [comment]
Done! `pixi-spine@3.0.0` supports `3.7`, `3.8`, `4.0`, and this `3.7` also can eat up easy models from previous versions, because it has special fixes in its parser. If you want to improve support of `3.6` and `3.5`, you can make PR that changes `packages/runtime-3.7` folder

**Comment by ivanpopelyshev** [comment]
@st3v0 need your feedback

**Comment by st3v0** [comment]
Sorry @ivanpopelyshev I'm no longer in a position to test these changes. I've moved on from that role.

**Comment by ivanpopelyshev** [comment]
@st3v0 people tested it, it works, so your idea and thread was very helpful!
