### ISSUE TITLE
Support for PIXI v6

### ISSUE THREAD

**Issue by qtiki** [pixijs/spine#379]
I'm guessing this is already in the works but I opened this issue anyway to have a place to track the progress.

Adding `pixi.js` and `pixi-spine` with their latest versions (v6.0.0 and v2.1.11 respectively) will result in a bunch of errors when trying to use them together in a TypeScript project.

These errors come simply by trying to import both packages:
```ts
import * as PIXI from 'pixi.js';
import 'pixi-spine';
```

The errors mostly look like this:
```
node_modules/pixi-spine/dist/pixi-spine.d.ts:594:22 - error TS2694: Namespace 'PIXI' has no exported member 'Matrix'.

594         matrix: PIXI.Matrix;
                         ~~~~~~
```

**Comment by ivanpopelyshev** [comment]
thanks!

**Comment by grnch-net** [comment]
Any update on this? :)

**Comment by ivanpopelyshev** [comment]
Yes, you can build it from https://github.com/pixijs/pixi-spine/tree/next , npm link `bundles/pixi-spine/` and all the `packages` folders

**Comment by ivanpopelyshev** [comment]
I'm working on publishing it. Do you need this thing for 3.7 , 3.8 or 4.0 spine?

**Comment by grnch-net** [comment]
spine 3.8, please

**Comment by gpoole** [comment]
I think it's confusing that the current README in master is not valid for the published version of pixi-spine. Most people trying to set up a new project with the latest versions of pixi and pixi-spine are going to have this problem and the README is the first result on Google when searching for this project.

**Comment by ivanpopelyshev** [comment]
Yep, I had a problem with publishing it.

Now its ready! HUZZAH!!!!

**Comment by gpoole** [comment]
Awesome, thanks @ivanpopelyshev

**Comment by grnch-net** [comment]
If you get error:
`Uncaught TypeError: Cannot redefine property: Spine`

Use hot fix:
```
const objectDefineProperty = Object.defineProperty;
Object.defineProperty = function(obj, prop, descriptor) {
  descriptor = {
    configurable: true,
    ...descriptor
  };
  objectDefineProperty(obj, prop, descriptor);
}
import 'pixi-spine';
```

**Comment by ivanpopelyshev** [comment]
wait WHAT? whats is wrong there?

**Comment by ivanpopelyshev** [comment]
Does problem exist only for `pixi-spine` or it exists for `@pixi-spine/all-3.8` too?

**Comment by grnch-net** [comment]
I am using npm module:
`npm i pixi-spine`;
import on my project:
`import * as spine from 'pixi-spine';`
build with gulp+tsify, tsconfig:
```
{
  files: ['libraries/main.ts'],
  moduleResolution: 'node',
  esModuleInterop:  true,
  paths: {
    'mini-signals': ['node_modules/resource-loader/typings/mini-signals.d.ts']
  },
  baseUrl: './'
}
```
and I get error:
`Uncaught TypeError: Cannot redefine property: Spine`

**Comment by grnch-net** [comment]
[test.zip](https://github.com/pixijs/spine/files/6411977/test.zip)
`npm i`
`gulp`

**Comment by JonnyCodes** [comment]
I'm having the same issue as above, any update on that?
I only see the issue when running jest tests though.
The hot fix @grnch-net posted works 👍 , but would be nice to have a proper solution.

**Comment by ivanpopelyshev** [comment]
I can try remove this line: https://github.com/pixijs/spine/blob/5bb2c001962e0f24a07ebb9b053e2131090275d9/bundles/pixi-spine/src/index.ts#L3 and see if it works. Can you do it in your `node_modules/pixi-spine` and confirm that it works now?

If so, I'll release new version. However, all version-related spine classes will exist only in `@pixi-spine/runtime-3.8` and so on, and wont be re-exported by main pixi-spine. You'll have to use `@pixi-spine/all-3.8` if you are 3.8-only to not import classes from runtime.

**Comment by JonnyCodes** [comment]
That worked. Thanks.
I'll look into using a specific version of the runtime, like `@pixi-spin/all-3.8` or something, tomorrow

**Comment by ivanpopelyshev** [comment]
OK, gonna up version today or tomorrow.

**Comment by ivanpopelyshev** [comment]
OK, i made release `3.0.3`, can you guys check it?

**Comment by JonnyCodes** [comment]
Will check it in the morning. Thanks for jumping on it so quickly :)

**Comment by JonnyCodes** [comment]
Just tested `3.0.3` and it works! Thanks again
