### ISSUE TITLE
Strange IK problems for 4.0

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/spine#388]
Got it here: https://codesandbox.io/s/pixi-spine-30-test-0iopd

"hoverboard" animation is a bit wrong.

![image](https://user-images.githubusercontent.com/695831/116736299-5f40d500-a9f8-11eb-89a9-ce4a78129ec2.png)

**Comment by ivanpopelyshev** [comment]
UPD. @badlogic said it might be spine-ts 4.0 issue

**Comment by badlogic** [comment]
Sorry for the late reply. Could you give the latest 4.0 commit a try. Also make sure to use the latest export.

**Comment by ivanpopelyshev** [comment]
Oh thanks! gonna update and test now

**Comment by ivanpopelyshev** [comment]
Nope, IK is even more derped for me. I dont understand where my code in `master` different from current `spine-ts 4.0`. Of course I'm moving all those matrix fields from `Bone` to `Matrix` forces quite a few differences, but usually I see all the changes pretty fast.

**Comment by ivanpopelyshev** [comment]
The fact that spineboy-pro bones are different from previous version is not helping me in debug :)

**Comment by ivanpopelyshev** [comment]
Bwahahaha 

https://github.com/pixijs/spine/commit/ece14ccd5e235e449232e5dc6e8a724b8ee9daba
