### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'off' of null

### ISSUE THREAD

**Issue by kayac-chang** [pixijs/spine#389]
Version:
```
  "pixi.js": "^6.0.2",
  "@pixi-spine/all-3.8": "^3.0.1",
  "@pixi-spine/base": "^3.0.1",
  "@pixi-spine/runtime-3.8": "^3.0.1",
```

## Throw by:
```javascript
    public destroy(options?: IDestroyOptions|boolean): void
    {
        super.destroy(options);

        // Uncaught TypeError: Cannot read property 'off' of null
        this._texture.off('update', this._onTextureUpdate, this);  

        this._anchor = null;

        const destroyTexture = typeof options === 'boolean' ? options : options && options.texture;

        if (destroyTexture)
        {
            const destroyBaseTexture = typeof options === 'boolean' ? options : options && options.baseTexture;

            this._texture.destroy(!!destroyBaseTexture);
        }

        this._texture = null;
    }
```

## The current behavior
![Screen Shot 2021-05-03 at 6 16 05 PM](https://user-images.githubusercontent.com/32451546/116865144-a2d75100-ac3b-11eb-9472-5a90e57f7b8a.png)

**Comment by ivanpopelyshev** [comment]
looks like double-destroy. Any ideas how to fix it?

**Comment by kayac-chang** [comment]
```js
class CustomSpine extends _Spine {
  destroy(options?: any): void {}
}
```

This solution only solves my issue temporary, 
I might need some time on figuring out the root cause.

**Comment by adsko** [comment]
@kayac-chang @ivanpopelyshev It looks like you're using react-pixi, where on destroy is called:
```
  if ((_child$children = child.children) !== null && _child$children !== void 0 && _child$children.length) {

    _toConsumableArray(child.children).forEach(function (c) {
      _removeChild(child, c);
    });
  }

  parent.removeChild(child);
  child.destroy();
```

So, react-pixi at first removes a spine children and calls his destroy, and next calls destroy on the spine. Because of it, we have called destroy on destroyed object.

**Comment by adsko** [comment]
@kayac-chang @ivanpopelyshev React-pixi@6.6.2+ have added config, which prevents destroying children. 
See: https://reactpixi.org/custom-components#config 
`destroyChildren` should fix the issue. At least for me, it helped.
