### ISSUE TITLE
Property 'setAnimation' does not exist on type 'IAnimationState'.ts(2339)

### ISSUE THREAD

**Issue by MercurialUroboros** [pixijs/spine#390]
Hi.

I'm trying to use the most basic example for pixi-spine using version 3.0.1 with pixi 6.0.4.

```
    const animation = new Spine(resources.timer.spineData);
    animation.state.setAnimation(0, 'run', true)
    // add the animation to the scene and render...
    app.stage.addChild(animation);
```

The setAnimation will be underlined in red showing Property 'setAnimation' does not exist on type 'IAnimationState'.ts(2339).
At runtime although, it works. So it must be some declaration file acting out.

**Comment by ivanpopelyshev** [comment]
Current version of `pixi-spine` supports all spine runtimes, so I have to generalize interfaces.

How to fix that thing:

1. You can make PR and add it there. I just didnt add all universal functions in those interfaces
2. alternatively, use `@pixi-spine/all-3.8`

**Comment by FloodGames** [comment]
Is it related to this? 
![image](https://user-images.githubusercontent.com/60991890/118417288-b2cb4800-b6b3-11eb-866d-708f9c0661e6.png)

**Comment by ivanpopelyshev** [comment]
6.0.4 is "^6.0.2" , right?

**Comment by ivanpopelyshev** [comment]
OK, please give me minimal example, i'll look. It seems that I dont use the same tsconfig as you )

**Comment by MercurialUroboros** [comment]
Well the reproduction code is as simple as

```
import { Application } from 'pixi.js'
import { Spine } from 'pixi-spine'

const app = new Application()

document.body.appendChild(app.view)

app.loader
  .add('timer', 'assets/timer.json')
  .load(function (loader, resources) {
    console.log(resources)
    const animation = new Spine(resources.timer.spineData);

    animation.state.setAnimation(0, '10sec Timer', true)
    // add the animation to the scene and render...
    app.stage.addChild(animation);

  });

```

Using     
"pixi-spine": "^3.0.1",
"pixi.js": "^6.0.4",

**Comment by ivanpopelyshev** [comment]
need tsconfig :)

**Comment by MercurialUroboros** [comment]
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client"],
    "baseUrl": ".",
    "paths": {
      "mini-signals": [
        "node_modules/mini-signals/index.js"
      ]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
}

```

**Comment by ivanpopelyshev** [comment]
btw, here's example how to improve interfaces for general version: https://github.com/pixijs/spine/issues/399
