### ISSUE TITLE
interactive throws with using the UMD pixi.js

### ISSUE THREAD

**Issue by Benjamin-Zh** [pixijs/spine#396]
Hi there. I'm using pixi 6 and spine 4.

When the pixi.js is imported by script tag(umd package) and set interactive property to true on a spine object, then tap anywhere on the stage, an error will be raised. But when the pixi.js is imported by npm(es modules), everything will be just ok.

Here is the error stack:
![image](https://user-images.githubusercontent.com/48583141/125462336-5b933ecf-a806-4286-8784-777ec15a6de6.png)

![image](https://user-images.githubusercontent.com/48583141/125462565-9374f310-4c17-4f19-85df-4d9aa03e2231.png)

Please have a look, thanks a lot :)

**Comment by ivanpopelyshev** [comment]
Spine does not have its own interaction, so its probably something in latest pixi, if you make zip-file with umd stuff i'll debug it.

**Comment by Benjamin-Zh** [comment]
Failed to send the email, seems like gmail blocked it. 😂

You can download the zip package here:
[http://cdn.benjamin.fun/spine-pixi-demo.zip](http://cdn.benjamin.fun/spine-pixi-demo.zip)

**Comment by ivanpopelyshev** [comment]
Most probably, spine uses pixi from node_modules, not the global one. Two pixies - whole lot of problems. I can make new `all-4.0` package that'll have UMD, is that fine for you?

**Comment by ivanpopelyshev** [comment]
OK, done: https://www.npmjs.com/package/@pixi-spine/all-4.0

It has UMD in `dist/` folder.

Never mind that readme says `3.8`, i forgot to change it

**Comment by Benjamin-Zh** [comment]
thanks a lot! it works.
