### ISSUE TITLE
Missing addListner from IAnimationState in V3

### ISSUE THREAD

**Issue by abhishekrathore03** [pixijs/spine#399]
Hi Guys,

I was trying to migrate from V2 to V3.
While migrating noticed that IAnimationState is missing the function addListner, however this function is present in runtime 3.7, 3.8 & 4.0

Requesting you to please export this function as well.
We are using this to bind some of our frameworks events.

Happy to do a PR if required.

Glad to see the new and improved version of PIXI-Spine, Thanks a lot to @ivanpopelyshev and team for building this up.

**Comment by ivanpopelyshev** [comment]
Yes, i'll add it, however you can use `@pixi-spine/all-3.8` or `@pixi-spine/all-4.0`, that way you wont need those interfaces at all, you'll see direct types

**Comment by abhishekrathore03** [comment]
but that will limit us to a specific version?
What if i want to be able to use both types of spines 3.8 & 4.0 ?

**Comment by ivanpopelyshev** [comment]
Well, probably, need `IAnimationStateListener` which  will depend on `ITrackEvent`, and we need `IEvent` for one of functions. Its 5-10 minutes of work, care to make PR?

**Comment by abhishekrathore03** [comment]
Sure, on it
can you please tell me how can i access `AtlasAttachmentLoader`?

**Comment by ivanpopelyshev** [comment]
Its version-dependant runtime factory, and interface for it is also version-dependant, you have to create universal version of it (with IMeshAttachment and so on) if you want to use it.

How the heck did you dig down from event listeners to it ? :)

==============
Just want to clarify, I will copy this post in other issues when people ask
==============

I moved everything to new rails so users wont have problem helping me with it :) I laid the foundation, now I want just to merge PR's. Previously I had to reject several PR's related to spine versions and I felt bad about it.

I think that new `pixi-spine` is the only runtime that gives the possibility to use models of different file formats/models. Official EsotericSoftware stance is that when you update the editor - you have to update all your spine models and your runtime, there's no fallback.

I'm not sure how to make universal interfaces so I need help with it.

**Comment by ivanpopelyshev** [comment]
Can you check new 3.0.7 release?

**Comment by abhishekrathore03** [comment]
Yes, works fine
Thanks a lot :)
