### ISSUE TITLE
Pixi.js v6.1.0 and Spine v3.0.7

### ISSUE THREAD

**Issue by rkrasky** [pixijs/spine#403]
Apparently the loader was changed in PIXI 6.1.0. Is it possible that the SpineParser no longer works correctly? For me, only the JSON files are loaded, no images and no Atlas files. The spineData is also not available.

**Comment by ivanpopelyshev** [comment]
yes, working on that right now. I was the one who embedded loader in 6.1.0 and forgot to test it with spine :(

**Comment by rkrasky** [comment]
Great! Thank you so much for responding so quickly and fixing it already!

**Comment by ivanpopelyshev** [comment]
Can you check `3.0.8` right now?

**Comment by rkrasky** [comment]
Works like clockwork! Works fine with 3.0.8 and Pixi.js 6.1.0! Thanks a lot!
