### ISSUE TITLE
@pixi-spine/all-4.0 - AnimationStateListener functions should be optional

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/spine#412]
- only a problem for `state.addListener`, adding a listener to an individual track works as expected.
- limited to `@pixi-spine/all-4.0` - `@pixi-spine/all-3.8`, and the main `pixi-spine` package work as expected.

Due to this, code like this will not work, since all the functions have to be present:

```
const listener = {
    event:(entry,ev)=>{
        ...
    }
}
spine.state.addListener(listener);
```

I've tested that it works by casting the listener to AnimationStateListener, so we know the runtime isn't calling functions that aren't defined.

In @pixi-spine/all-3.8 (correct)

```
export declare interface AnimationStateListener extends IAnimationStateListener {
    /** Invoked when this entry has been set as the current entry. */
    start?(entry: TrackEntry): void;
    /** Invoked when another entry has replaced this entry as the current entry. This entry may continue being applied for
     * mixing. */
    interrupt?(entry: TrackEntry): void;
    /** Invoked when this entry is no longer the current entry and will never be applied again. */
    end?(entry: TrackEntry): void;
    /** Invoked when this entry will be disposed. This may occur without the entry ever being set as the current entry.
     * References to the entry should not be kept after dispose is called, as it may be destroyed or reused. */
    dispose?(entry: TrackEntry): void;
    /** Invoked every time this entry's animation completes a loop. */
    complete?(entry: TrackEntry): void;
    /** Invoked when this entry's animation triggers an event. */
    event?(entry: TrackEntry, event: Event_2): void;
}
```

in @pixi-spine/all-4.0 (all functions should be optional as in 3.8)

```
export declare interface AnimationStateListener extends IAnimationStateListener {
    /** Invoked when this entry has been set as the current entry. */
    start(entry: TrackEntry): void;
    /** Invoked when another entry has replaced this entry as the current entry. This entry may continue being applied for
     * mixing. */
    interrupt(entry: TrackEntry): void;
    /** Invoked when this entry is no longer the current entry and will never be applied again. */
    end(entry: TrackEntry): void;
    /** Invoked when this entry will be disposed. This may occur without the entry ever being set as the current entry.
     * References to the entry should not be kept after dispose is called, as it may be destroyed or reused. */
    dispose(entry: TrackEntry): void;
    /** Invoked every time this entry's animation completes a loop. */
    complete(entry: TrackEntry): void;
    /** Invoked when this entry's animation triggers an event. */
    event(entry: TrackEntry, event: Event_2): void;
}
```

**Comment by ivanpopelyshev** [comment]
Its the same as in https://github.com/EsotericSoftware/spine-runtimes/blob/db92cb3667c88bb819bd24c09f839529e0df4aa5/spine-ts/spine-core/src/AnimationState.ts#L1096-L1116

If you think it can be optional, you can make PR's both here and in main repo

**Comment by jmlee2k** [comment]
Hi Ivan, thanks for the response.  I noticed they weren't optional in https://github.com/EsotericSoftware/spine-runtimes, but they also weren't optional in their 3.8 branch, so I thought you may be doing something custom here.

I was going to make a PR, but I'm not exactly sure where the code for the @pixi-spine/all-4.0 package is.

**Comment by ivanpopelyshev** [comment]
looks like it : https://github.com/pixijs/spine/blob/master/packages/runtime-4.0/src/core/AnimationState.ts#L1180-L1200

**Comment by jmlee2k** [comment]
Great, thanks, I was looking the bundles dir. :|

I'll make a PR soon.

**Comment by smlmyck** [comment]
Is there any chance this fix could be released through NPM? We've just swapped to Spine 4.0 and we're now seeing this issue using the current latest (3.0.13) of @pixi-spine/all-4.0, would save us some `any`s.
