### ISSUE TITLE
PIXI.spine.core is undefined

### ISSUE THREAD

**Issue by Amarillys** [pixijs/spine#424]
Hello.

I have tried to preload json according to the example, but an error occurred:

PIXI.spine.core is undefined.

https://github.com/pixijs/spine/blob/master/examples/preloaded_json.md

And this is the js I imported:
https://cdn.jsdelivr.net/npm/pixi-spine@3.0.13/dist/pixi-spine.umd.js

Thanks!

**Comment by Amarillys** [comment]
I have imported the runtime-3.7 and found that it defined at _pixi_spine_runtime_

**Comment by ivanpopelyshev** [comment]
If you use only 3.7 models , you can use `@pixi-spine/all-3.7` package instead, I believe its UMD has all runtime classes in `PIXI.spine` scope

**Comment by Amarillys** [comment]
Thanks for replying.
But npm said that @pixi-spine/all-3.7 404 not found

npm i @pixi-spine/all-3.7
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@pixi-spine%2fall-3.7 - Not found

I use all-3.8 and it said that cannot load versio.3.3.07
In addition, the atlasAttachmentLoader function is in PIXI.spine instead of PIXI.spine.core according to the examples.

**Comment by ivanpopelyshev** [comment]
Oh, right, you have to do it yourself. See https://github.com/pixijs/spine/tree/master/bundles ? You can make all-3.7 accordingly, add it to https://github.com/pixijs/spine/blob/master/rush.json and `rush build` should give you UMD.

3.7 is too old, i was too lazy to make this package. If its not enough, please bother people at https://github.com/pixijs/pixi.js/discussions, im temporarily not working on pixi.

**Comment by Amarillys** [comment]
Okay, thank you! I will try it!

**Comment by ivanpopelyshev** [comment]
so, basically:

1. clone the repo
2. add all-3.7 , change files accordingly
3. `rush update`
4. `rush build`, i think...
5. The result is in UMD file.

maybe you need both `rush` and `pnpm` installed globally. Yes, I over-engineered this repo.

Alternatively, if you can use ES6 modules:
1. take all3.8 js file, copy in your project, change to 3.7 
2. it works.
