### ISSUE TITLE
Load spine model from zip with jszip

### ISSUE THREAD

**Issue by jomin398** [pixijs/spine#430]
unzipped zip file with jszip..
Then  i tryed display image  on the page
from it, it works.
(Img src with blob.)
But i tryed asset loader with a blob link, the image cannot be loaded.
It throws like image is not exist.

`BaseImageResource.js:76 WebGL: INVALID_VALUE: texImage2D: invalid image`

**Comment by jomin398** [comment]
i make it work some times...
WHY IT'S WORKS SOME TIMES????
```js
function method(arr){
    // 0:skelJson,1:rawSkel, 2:atlas, 3:zip, 4:links, 5:iArr, 6:iNrr;
    // 
    console.log(arr[3])
    //your skeleton.json file here
    var spineAtlas = new PIXI.spine.core.TextureAtlas(arr[2], function (line, callback) {
          // pass the image here.
          // iNrr is rawSkeletonData.skeleton.images array.
          // iArr is blob urls
          // overwrite .png (image file) to blob url;
          callback(arr[5][arr[6].indexOf(line)])
     }); // specify path, image.png will be added automatically
    var spineAtlasLoader = new PIXI.spine.core.AtlasAttachmentLoader(spineAtlas)
    var spineJsonParser = new PIXI.spine.core.SkeletonJson(spineAtlasLoader);
    var spineData = spineJsonParser.readSkeletonData(arr[1]);
    spineData.imagesPath = arr[5];
    return Promise.resolve(spineData);
}
method.then(new PIXI.spine.Spine)
```
some time throws ERROR... in
`method.then(new PIXI.spine.Spine)` throw `BaseImageResource.js:76 WebGL: INVALID_VALUE: texImage2D: invalid image`

**Comment by ivanpopelyshev** [comment]
Currently there's a shortage of staff for this plugin, so you have to ask somebody at https://github.com/pixijs/pixijs/discussions/ with link to this issue. 

I can only say it that its possible :)

**Comment by jomin398** [comment]
I moved out of pixi due to customizing spine engine.
Now I'm Using spine-ts/spine-player
