### ISSUE TITLE
Weird square around character in production? 

### ISSUE THREAD

**Issue by JashanKhela** [pixijs/spine#433]
Hey all, happy coding :)

New to PIXI and building a small game! I am using one of the plugins to create my character using Spine! Everything was going great until I pushed the code to production and now there is a weird square around my character only in production?
 

https://bc-beta-testing.netlify.app/

Any help is greatly appreciated!

**Comment by ivanpopelyshev** [comment]
when you export texture , make sure "premultiply alpha" is not checked.

**Comment by JashanKhela** [comment]
Thanks @ivanpopelyshev ! I will re-export it and report back! You are the best

**Comment by JashanKhela** [comment]
Worked like a charm! Just out of curiosity, how did you know how to debug that? :) 

You rock!

**Comment by ivanpopelyshev** [comment]
because we had many problems with PMA both in pixijs and spine, i had to write shaders for spine that were ported to other runtimes too.

http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/
