### ISSUE TITLE
Help with migrating v2 -> v3

### ISSUE THREAD

**Issue by asiryk** [pixijs/spine#439]
Hi! I used to use npm "pixi-spine" v2.1.8 and I want to upgrade to the latest 3.0.1.
I get that now instead of `PIXI.spine.Spine` I have to use `import { Spine } from "pixi-spine";`.

But what about `PIXI.spine.core.TrackEntry`, `PIXI.spine.core.Animation`?
How do I import those type declarations? I see now you have ITrackEntry, but seems there is no possibility to import it.

The declaration file doesn't have those types.

``` typescript
import { SkeletonBounds } from '@pixi-spine/runtime-4.0';
import { Spine } from '@pixi-spine/loader-uni';
import { SpineParser } from '@pixi-spine/loader-uni';
export { SkeletonBounds }
export { Spine }
export { SpineParser }

export * from "@pixi-spine/base";

export { }

```

Could someone help me with that? Or is there a migration guide? All examples are using the v2 approach.

**Comment by ivanpopelyshev** [comment]
Three ways
1. Either you import everything from `@pixi-spine/all-4.0`  , it re-exports everything from 4.0 runtime
2. either you  modify interfaces :
3. either you make your own bundle like that all-4.0

TrackEntry and Animation are from `runtime-4.0`. or `runtime-3.8`, depends on spine model version. Default `pixi-spine` provides all of them - you have to use interfaces with it

**Comment by asiryk** [comment]
Aha, got you, thanks!
