### ISSUE TITLE
IK setting bones with wrong Rotation

### ISSUE THREAD

**Issue by diegomachado** [pixijs/spine#441]
When using simple IKs on my character's feet, they stay pointed up when imported.
It works perfectly when using `spine-ts` or Unity.

![pixi-spine-ik-issue](https://user-images.githubusercontent.com/104657/166296334-cf721c0a-015c-4ff2-b36f-18b431814677.png)

The feet get corrected if I set the IK's Mix parameter to 0 on Spine, but then all animations break because that basically deactivates the IK, and that's why I know this is the root of the issue.

Using Spine 3.8 export didn't work either, nor using previous versions of the plugin.

Unfortunatelly I can't provide the source file due to IP's restrictions, but I think updating the plugin to the latest official runtime would fix it.

## Environment
Spine: 4.0 Pro
pixi.js: 6.3.0
pixi-spine: 3.0.13
Same behavior on Chrome, Firefox and Brave

**Comment by ivanpopelyshev** [comment]
Finally found it. 3.0.16 is fixed.

**Comment by diegomachado** [comment]
Sorry for the late reply @ivanpopelyshev, just tested and it's all working as expected with the latest updates! 👍 
Thanks!
