### ISSUE TITLE
Get current track animation

### ISSUE THREAD

**Issue by impguard** [pixijs/spine#449]
I'm trying to reconcile this library with Spine documentation and I can't seem to find a way to get the current running animation on a track. The TrackEntry type doesn't seem to contain the animation name unlike in spine docs.

On a separate note, is there a clear way to understand how spine interfaces are exposed by this library or is it a custom wrapper so I just have to look through the documentation here?

**Comment by ivanpopelyshev** [comment]
Try use specific version, like `@pixi-spine/all-4.0`

**Comment by impguard** [comment]
Good call. I presumed that pixi-spine was latest but apparently it's an older version. Thanks!
