### ISSUE TITLE
Combining Skins

### ISSUE THREAD

**Issue by FloodGames** [pixijs/spine#456]
With the new version, "Skin" can no longer be imported. How should I combine skins?

```
function combineSkin(spineObject: SpineExtended) {
  // create new empty skin
  const newSkin = <any>new Skin("combined-skin")
  // add base skin
  newSkin.addSkin(spineObject.spineData.findSkin("Shirts/shirtDefault"))
  // add parital skins over base
  newSkin.addSkin(spineObject.spineData.findSkin("Back/backDefault"))
  newSkin.addSkin(spineObject.spineData.findSkin("Masks/maskDefault"))
  newSkin.addSkin(spineObject.spineData.findSkin("Tails/tailDefault"))
  newSkin.addSkin(spineObject.spineData.findSkin("Belts/beltDefault"))
  newSkin.addSkin(spineObject.spineData.findSkin("Shoes/shoesDefault"))
  newSkin.addSkin(spineObject.spineData.findSkin("Hats/hatDefault"))
  newSkin.addSkin(spineObject.spineData.findSkin("Eyes/eyesDefault"))
  spineObject.skeleton.setSkin(newSkin)
  // console.log(newSkin)
  spineObject.skeleton.setSlotsToSetupPose() //Reset slots to remove not used attachments
}
```

**Comment by ivanpopelyshev** [comment]
which package do you use?

**Comment by FloodGames** [comment]
> which package do you use?

I tried upgrading to:
```
    "pixi-spine": "3.1.0",
    "pixi.js": "6.5.2",
```

**Comment by FloodGames** [comment]
I think just applying each skin consecutively without calling 'setSlotsToSetupPose' does exactly that
```
  spineObject.skeleton.setSkinByName("Shirts/shirtDefault")
  spineObject.skeleton.setSkinByName("Hats/hatDefault")
  spineObject.skeleton.setSkinByName("Eyes/eyesDefault")
  // spineObject.skeleton.setSlotsToSetupPose()
```

**Comment by FloodGames** [comment]
Not quite, still need the original Skin method

**Comment by ivanpopelyshev** [comment]
if you use only 4.0 , you can take `@pixi-spine/all-4.0` instead of `pixi-spine` . This is mentioned in README a few times I believe - main package contains all runtimes and uses interfaces instead of direct types. Specific packages have only one runtime and original types.

**Comment by FloodGames** [comment]
> @pixi-spine/all-4.0


haha, I'm such an idiot. 
import { Skin } from "@pixi-spine/runtime-4.1" works instead of "@pixi-spine/runtime-4.0" - it's just that my vscode doesn't detect the Skin import when crtl-spacebar it. 

Can you edit this page to include the import statement ?
https://github.com/pixijs/spine/blob/379b4d852dcf2fa0e007cb2a60428e38afbb0c9e/examples/change_skin.md
