### ISSUE TITLE
Clone spine instance to add on stage

### ISSUE THREAD

**Issue by 4tech-jacky** [pixijs/spine#462]
Can I load a json file, then add multiple of it instance to stage. Example:
app.loader
        .add('a', '/assets/animation/skeleton.json')
        .load((loader, resources) => {

              const a = new SPINE.Spine(resources.a.spineData)

              app.stage.addChild(a)

              const b = new SPINE.Spine(resources.a.spineData)

              b.position.x = 10

              app.stage.addChild(b)
}
I already tried above code but it not works as expected, only the first one is added

**Comment by ivanpopelyshev** [comment]
that's how its supposed to work.

**Comment by 4tech-jacky** [comment]
> 

So can we have any way to do something like that, clone Spine using the same source

**Comment by 4tech-jacky** [comment]
It seems my mistake, it works now. Thanks
