### ISSUE TITLE
Pixi v7 support

### ISSUE THREAD

**Issue by alexbown** [pixijs/spine#463]
In Pixi v7 (currently on alpha 3), [PIXI.Loader](https://pixijs.download/v6.1.1/docs/PIXI.Loader.html) is removed and [PIXI.Assets](https://pixijs.download/v7.0.0-alpha.3/docs/PIXI.Assets.html) is used in its place, will this update be supported in pixi-spine?

**Comment by ivanpopelyshev** [comment]
Yep, working on that :)

**Comment by yungzhu** [comment]
7.0 It has been released. What's new

**Comment by yungzhu** [comment]
@ivanpopelyshev Expect a new version

**Comment by Giacom** [comment]
Looking forward as well!

**Comment by skaboy007** [comment]
Good day. 
Hi, do you have a roadmap release date for Pixi 7 support?

**Comment by ivanpopelyshev** [comment]
Yes I have a plan to be implemented as soon as i leave my sofa :)

**Comment by skaboy007** [comment]
nice one, but seriously. it would be very nice узнать when to expect it. as we are considering developing a port ourselves for internal use. at least a rough estimate.

**Comment by ivanpopelyshev** [comment]
this week )

**Comment by skaboy007** [comment]
nice ^__^

**Comment by st-volodymyr** [comment]
> this week )

any update about this?

**Comment by ivanpopelyshev** [comment]
I'm overworked. Hope to solve this tomorrow and the day after

**Comment by ivanpopelyshev** [comment]
OK guys, I've tried to build it, it required update build tools, and I failed.

I'm asking @miltoncandelero to deal with that thing.

**Comment by erik0612** [comment]
is it possible to load spine data by using PIXI.Assets? and if so, how can I load spine data?

**Comment by miltoncandelero** [comment]
Not yet, I am working on it on the `pixi-v7` branch but I still have some way to go

**Comment by erik0612** [comment]
got it. thanks @miltoncandelero

**Comment by miltoncandelero** [comment]
`pixi-spine` now supports PixiJS v7! :partying_face: 

- Please check that if you want to use PixiJS v7 you will need `pixi-spine` **v4.x**
- To use `pixi-spine` on previous PixiJS (v6 or v5) you will need **v3.x**

https://www.npmjs.com/package/pixi-spine
https://github.com/pixijs/spine

**Comment by erik0612** [comment]
seems it's working with @pixi/node as well. thanks @miltoncandelero 
Also tested with pixi.js. it's working!

**Comment by Stanko998** [comment]
how to add pixi-spine v4 in pixi v7 project? can any explain me this pls?

**Comment by erik0612** [comment]
it's in the readme https://github.com/pixijs/spine

**Comment by erik0612** [comment]
@miltoncandelero it's working assets load on mac m1
like
```
    PIXI.Assets.add('animation', 'assets/spine/animation.json');
```
but it's not working on non m1 machine.

**Comment by miltoncandelero** [comment]
> @miltoncandelero it's working assets load on mac m1
> like
> ```
>     PIXI.Assets.add('animation', 'assets/spine/animation.json');
> ```
> but it's not working on non m1 machine.

Do you have an error log or something?

**Comment by erik0612** [comment]
@miltoncandelero I figured out it. it was because of directory name of project.
it was just like `image.xxxx` and it detected as extname at `@pixi/utils/path.js` 167 line.

**Comment by MayankDhankhar** [comment]
> @miltoncandelero it's working assets load on mac m1 like
> 
> ```
>     PIXI.Assets.add('animation', 'assets/spine/animation.json');
> ```
> 
> but it's not working on non m1 machine.

Hi, I think you have to add import for pixi-spine like this at the top where you are loading : 
import 'pixi-spine';
