### ISSUE TITLE
SpineLoader not using runtime-4.0? And a minor issue on SpineDebugRenderer

### ISSUE THREAD

**Issue by hmpthz** [pixijs/spine#464]
Firstly a disclaimer, I'm not an expert on Spine, honestly I know nothing about those things like version, attachments, etc. This is how I find this problem:

The latest `SpineDebugRender` has not yet been released on npm so I built it manually. When I tried to use it, there's an error said "regionAttachment.updateOffset() is not a function".
It appears that at `SpineDebugRenderer.ts, line:284`, the `updateOffset()` function is optional. For example the RegionAttachment from runtime-4.1 doesn't have it. So I added a simple check to see if this function exists, and built again, it worked.

Which brings me to the second problem: The spine asset I used was version 4.0, why did the library use runtime-4.1?
At `SpineLoader.ts, line:55`, I can see that both version 4.0 and version 4.1 use runtime-4.1, is there a particular reason of why?

**Comment by ivanpopelyshev** [comment]
runtime-4.1 is backwards compatible to 4.0 
Didnt know about `updateOffset`, my bad ) i'll return updateOffset then

**Comment by hmpthz** [comment]
Thanks that sounds good. If this function is not optional, then `SpineDebugRenderer` has nothing to be fixed.
