### ISSUE TITLE
Using PIXI.Loader.Shared does not parse spine data

### ISSUE THREAD

**Issue by Technostalgic** [pixijs/spine#471]
Hello, I am using PixiJS spine runtime from this repository installed with `pnpm install pixi-spine`

the code below:
```
		let loader = PIXI.Loader.shared;
		loader.add('SpineBG', "./assets/spine/background_animation.json",
			function(resource){
				console.log(resource.spineData);
			});
		loader.load();
```
causes the the `resource.spineData` to evaluate to `undefined`. But if I simply change it to:
```

		let loader = new PIXI.Loader();
		loader.add('SpineBG', "./assets/spine/background_animation.json",
			function(resource){
				console.log(resource.spineData);
			});
		loader.load();
```
It works with no issues and the spine data object is loaded and parsed property. This caused me lots of trouble since it took me a while to figure out what the issue was, and I was very surprised to see that the issue had not been reported on here yet. It might have something to do with my project setup, but I doubt it since I have not modified the pixi-spine settings or files at all.

If you need more information to resolve the issue please let me know.

**Comment by ivanpopelyshev** [comment]
The issue is the order of creation of modules. I dont believe anyone should fix it, it can break at any moment because of different webpack config.

**Comment by Technostalgic** [comment]
Yeah that makes sense, I just thought it might be useful to mention here
