### ISSUE TITLE
Bug: Assets.load automatically loads the Spine image path is incorrect

### ISSUE THREAD

**Issue by bambooGHT** [pixijs/spine#487]
### Current Behavior

When loading pictures, the address will be changed to port 5173 =>
 http://localhost:5173/localhost:3001
![image](https://user-images.githubusercontent.com/101973620/222182228-ede30cc0-d3db-42cb-aa4f-7fb8d0ec998d.png)
![image](https://user-images.githubusercontent.com/101973620/222182296-8d42648c-6f70-4bf5-946b-fd2640271a53.png)

### Expected Behavior

Logically speaking, the original path should be applied =>http://localhost:3001/

### Steps to Reproduce

`const res=await Assets.load(""http://localhost:3001/character/ch_10013/ch_10013_0/ch_10013.json"")`

### Environment

- **`pixi.js` version**: *e.g. 7.1.3*
- **`pixi-spine` version**: *e.g. 4.0.3*

**Comment by bambooGHT** [comment]
![image](https://user-images.githubusercontent.com/101973620/222226148-5385939b-988f-4983-9f3d-184ec6078313.png)
The problem seems to be here:
  const url = lib_exports.path.join(...atlasBasePath.split(lib_exports.path.sep), pageName);
  
![image](https://user-images.githubusercontent.com/101973620/222226431-95465802-a78c-418c-82cf-504d0ef7ab07.png)
When the log is output, it is found that one "/" is missing.
If "/" is added, there will be no error
![image](https://user-images.githubusercontent.com/101973620/222230170-c7ed9a9d-60ef-436f-8569-80c6ea0d7f93.png)
![image](https://user-images.githubusercontent.com/101973620/222229806-358cd073-ef82-4b13-8894-73835c0afaa3.png)

**Comment by miltoncandelero** [comment]
but wait.. how did you end up with `http:/` ?
That is not correct syntax for a web protocol 🤔

**Comment by bambooGHT** [comment]
> but wait.. how did you end up with `http:/` ? That is not correct syntax for a web protocol 🤔
The following are google translations;

I'm not very clear, it's really strange that there is a missing "/" when loading the picture.
Also, I'm now running into a problem with premultiplication,
The following 2 settings are not effective.

`Assets.add(url, url, { imageMetadata: { alphaMode: ALPHA_MODES.PMA } });`
`const res = await Assets.load<spineData>(url, (progress) => {
 });`
 `// res.spineAtlas.pages.forEach(p => { `
 `//   p.baseTexture.alphaMode = ALPHA_MODES.PMA;`
 `// });`
 
It's a pity that I know too little about these knowledge.Is there a workable solution.

**Comment by ansbr** [comment]
Hello! I have the same error, looks like it takes incorrect path prefix from url.
In my case `pixi/` shouldn't be there
![image](https://user-images.githubusercontent.com/58120694/224339829-37a533db-afee-44b3-a308-5e0ca372027e.png)

**Comment by miltoncandelero** [comment]
what do you have inside your ball.atlas file? 🤔

**Comment by ansbr** [comment]
> what do you have inside your ball.atlas file? 🤔

```
ball.png
size:642,586
filter:Linear,Linear
pma:true
ball
bounds:2,12,572,572
offsets:1,1,574,574
shadow
bounds:576,2,582,64
offsets:3,4,588,72
rotate:90

```

**Comment by bambooGHT** [comment]
> Hello! I have the same error, looks like it takes incorrect path prefix from url. In my case `pixi/` shouldn't be there ![image](https://user-images.githubusercontent.com/58120694/224339829-37a533db-afee-44b3-a308-5e0ca372027e.png)

I remember this requires setting the base path,
`Assets.init({ basePath: 'http://localhost:3000/' });`
https://pixijs.download/release/docs/PIXI.Assets.html#init

**Comment by SisterWang** [comment]
> > 
> 
> > > but wait.. how did you end up with `http:/` ? That is not correct syntax for a web protocol 🤔
> > > The following are google translations;
> > 
> > 
> > I'm not very clear, it's really strange that there is a missing "/" when loading the picture. Also, I'm now running into a problem with premultiplication, The following 2 settings are not effective.
> > `Assets.add(url, url, { imageMetadata: { alphaMode: ALPHA_MODES.PMA } });` `const res = await Assets.load<spineData>(url, (progress) => { });` `// res.spineAtlas.pages.forEach(p => { ` `// p.baseTexture.alphaMode = ALPHA_MODES.PMA;` `// });`
> > It's a pity that I know too little about these knowledge.Is there a workable solution.
> 
> the solution => [pixijs/pixijs#9141](https://github.com/pixijs/pixijs/issues/9141)

I have encountered the same problem. Did you resolve this issue by downgrading to version pixi6?

**Comment by bambooGHT** [comment]
> > > 
> > 
> > 
> > > > but wait.. how did you end up with `http:/` ? That is not correct syntax for a web protocol 🤔
> > > > The following are google translations;
> > > 
> > > 
> > > I'm not very clear, it's really strange that there is a missing "/" when loading the picture. Also, I'm now running into a problem with premultiplication, The following 2 settings are not effective.
> > > `Assets.add(url, url, { imageMetadata: { alphaMode: ALPHA_MODES.PMA } });` `const res = await Assets.load<spineData>(url, (progress) => { });` `// res.spineAtlas.pages.forEach(p => { ` `// p.baseTexture.alphaMode = ALPHA_MODES.PMA;` `// });`
> > > It's a pity that I know too little about these knowledge.Is there a workable solution.
> > 
> > 
> > the solution => [pixijs/pixijs#9141](https://github.com/pixijs/pixijs/issues/9141)
> 
> I have encountered the same problem. Did you resolve this issue by downgrading to version pixi6?

链接里面有说了,可以直接修改源码解决这个问题,在node_modules搜索一下代码可以找到
