### ISSUE TITLE
How can I load spine from inline resources with new pixi loader?

### ISSUE THREAD

**Issue by Tygrain** [pixijs/spine#491]
I used to do it this way
```
...
import spineboy from './assets/spineboy.json' //base64 data url
import spineboy_atlas from './assets/spineboy.atlas'
import spineboy_texture from './assets/spineboy.png'
...
app.loader.add('spineboy', spineboy, {
    metadata: { 
        spineAtlasFile: spineboy_atlas,
        image: PIXI.BaseTexture.from(spineboy_texture)
    }
}).load(function (_loader, _resources) {
		...
})
```
now it doesn't work I get spineboy is null instead of spine
```
PIXI.Assets.add('spineboy', spineboy, { 
	metadata: {
	spineAtlasFile: spineboy_atlas,
	image: PIXI.BaseTexture.from(spineboy_texture)
}})
PIXI.Assets.load(['spineboy']).then(onLoaded)
```
Can you please tell me how I can transfer my atlas and texture to it when loading a spine asset?
I can try something like [this](https://github.com/pixijs/spine/issues/483#issuecomment-1406308009), but I would like to know if it is possible to make it easier

**Comment by SerG-Y** [comment]
@Tygrain you should pass your atlas in ```atlasRawData ``` like

`Assets.load({
				src: 'url',
				data: {
					atlasRawData: spineboy_atlas
				}
			});`

**Comment by Tygrain** [comment]
> @Tygrain you should pass your atlas in `atlasRawData ` like
> 
> `Assets.load({ src: 'url', data: { atlasRawData: spineboy_atlas } });`

this is apparently loading a texture with raw atlas data, but how can I transfer file spineboy.json, without it, the loader will not be able to create a spineData

I tried to study [this](https://github.com/pixijs/spine/blob/00a3ea2b2e7aef3a577cf1b0b23980633c3ba43a/packages/loader-base/src/SpineLoaderAbstract.ts#L89) code to understand how to collect all resources using the [PIXI.LoadAsset](https://pixijs.download/dev/docs/PIXI.LoadAsset.html) object but this method leads to an error `could not be loaded as we don't know how to parse it`, ensure the correct parser has being added, maybe loadParser is needed so that the loader understands what I'm trying to load

```
PIXI.Assets.load({
	src: spineboy, // data:application/json;base64, ...
	data: {
		atlasRawData: spinboy_atlas, // string
		image: PIXI.BaseTexture.from(spineboy_texture)
	}
})

```

**Comment by SerG-Y** [comment]
@Tygrain is I understood you correctly? You are trying to create spineData with already loaded data (json, atlas and texture)?

**Comment by Tygrain** [comment]
> 

into variables, sorry if I didn’t explain well, I have resources in the form of data url or raw string doesn’t matter, I need to understand how to pass them to the asset loader

**Comment by Tygrain** [comment]
@SerG-Y, I really appreciate your help with my code. Your approach works well. But I'm wondering why you can't initialize the SpineLoader resource loader with your own fields. Can you explain please?
