### ISSUE TITLE
Spine atlas with semver in url won't load textures correctly

### ISSUE THREAD

**Issue by heorhiy-kharvat** [pixijs/spine#493]
Hi,
my game spine assets are located on 'https://cdn.domain.com/game/1.2.3/resources/spine/*'
.atlas files are loaded correctly, but all textures .png files are attempted to load from 'https://cdn.domain.com/game/resources/spine/*'

Since 'makeSpineTextureAtlasLoaderFunctionFromPixiLoaderObject' uses 'core.utils.path.join'
extname for 1.2.3 is true, and before normalisation path for texture looks like
['https', 'cdn.domain.com', '..', 'game', '1.2.3', '..' 'resources', 'spine'] and that results corrupted texture url.

Anyway to fix that without modifying 'join' util or writing my own atlas parser?

**Environment:**
Chrome: 111.0.5563.64
pixi.js: 7.2.1
@pixi-spine/loader-3.8: 4.0.3
@pixi-spine/runtime-3.8: 4.0.3

**Potential solution:**
we could use just normalize and perform join of array of parts
`const url = core.utils.path.normalize([...atlasBasePath.split(core.utils.path.sep), pageName].join(core.utils.path.sep));`

Thanks :)

**Comment by SisterWang** [comment]
I encountered the same problem. Do you have any solutions now?

**Comment by heorhiy-kharvat** [comment]
I just have a temporary workaround, so it won't block our migration and testing on dev environment.
Patched https://github.com/pixijs/spine/blob/master/packages/loader-base/src/atlasLoader.ts#L100 locally to change it to potential solution line mentioned in issue description.

**Comment by JonnyCodes** [comment]
I've got the exact same issue.

Assets are being hosted at `https://www.domain.com/static/gameName/assets`
But when the textures are loaded from the atlas it is going to `https://www.domain.com/gameName/static/gameName/assets`.

Loader.mjs:77 -> utils.path.toAbsolute
Looks like assets fetched from the atlas don't start with a forward slash, so it is using the base url not the root url.

**Comment by florinnutiu** [comment]
We encountered same problem on Safari 14.1 and older, because url is missing a "/" after it passes through makeSpineTextureAtlasLoaderFunctionFromPixiLoaderObject from atlasLoader.
Waiting for a fix.

**Comment by klesun** [comment]
@miltoncandelero could you take a look, please? The library appears to be non-functional at current version due to that forward slash bug.

**Comment by miltoncandelero** [comment]
It's an upsteam bug and #500 won't fix the issue.

I will see how I can work arround it

**Comment by miltoncandelero** [comment]
Should be fixed in 4.0.4

**Comment by klesun** [comment]
Hm, I updated to 4.0.4, but png url is still lacking the leading slash resulting.

![image](https://github.com/pixijs/spine/assets/5202330/90f4b27e-f8b5-41b3-af15-b7c84cc84575)

**Comment by klesun** [comment]
I think your MR fixed a different issue (#9445) with paths than the one described here.

**Comment by florinnutiu** [comment]
4.0.4 fixed our Safari issue.
Thank u so much!
![image](https://github.com/pixijs/spine/assets/67897392/c4c72e3f-09a0-4358-a5b1-ab86697e2239)

**Comment by BALAGAASHOK** [comment]
[miltoncandelero](https://github.com/miltoncandelero)

I am using relative path for loading spine, sprite files. 

> const app = new PIXI.Application({ background: '#1099bb' });
>   document.body.appendChild(app.view);
>   // Add the assets to load
>   PIXI.Assets.add('spriteOne', '../assets/games/dist/spriteOne.jpg');
>   PIXI.Assets.add('spriteTwo', '../assets/games/dist/spriteTwo.jpg');
>   PIXI.Assets.add('spineboyPro', '../assets/games/dist/spineboy-pro.json');
> 
>   // Load the assets and get a resolved promise once both are loaded
>   const texturesPromise = PIXI.Assets.load(['spriteOne', 'spriteTwo', 'spineboyPro']);
>   // When the promise resolves, we have the texture!
>   texturesPromise.then((textures) => {
>     console.log(textures);
>     const spriteOne = PIXI.Sprite.from(textures.spriteOne);
>     app.stage.addChild(spriteOne);
>   });
> 
**I am getting 404 for spine png,but json & atlas files are getting loaded.**

![image](https://github.com/pixijs/spine/assets/21160256/eff3e22c-9bbd-4f80-a2ae-7b9cb9e7c11b)


**It's working for sprite but not spine files.**

![image](https://github.com/pixijs/spine/assets/21160256/1e9837fd-d800-4e84-a890-e8bf5ac2c033)

I am same using spine version of 4.0.4 but facing the same issue, can please take look

Pixi.js version 7.3
Pixi Spine version : 4.0.4

For your reference I am attaching sample project. Please find the link below;
[**code repo**](https://github.com/BALAGAASHOK/pixi-upgardeV7)

**Comment by JonnyCodes** [comment]
Finally got around to updating our version of pixi-spine and can confirm it's fixed in 4.0.4

Thanks for looking into it 👍
