### ISSUE TITLE
Spine loader concurrency (parallel asset fetching)

### ISSUE THREAD

**Issue by fenetic** [pixijs/spine#505]
Hello! I'm not deeply familiar with the inner-workings of pixi-spine so sorry if this is obvious, but I'm building an on-demand animation renderer which needs to rapidly respond to incoming requests.

One of the performance issues I need to address is getting to "render time" very quickly, which means optimising asset loading before a render happens.

Can anyone tell me if the Spine loader fetches skeleton data (image atlases) concurrently?

If it doesn't, what do I need to think about here? I looked in examples and saw a custom loader suggestion for Pixi <6.x -- we're using Pixi 7.x and pixi-spine 4.x

This is all happening on the backend so we're not limited by e.g. browser concurrency caps.

**Comment by miltoncandelero** [comment]
This is handled by `@pixi/assets` and I think it's parallelized and workerized already 🤔

**Comment by fenetic** [comment]
Thanks @miltoncandelero -- so I'm running this with `@pixi/node` and have a proxy endpoint for the assets which we store in S3 and cache on the renderer when needed; I'm seeing requests for the atlas assets consistently come in sequentially (in order) on `Assets.load(spineData)` which I would not expect if they were being fetched in parallel...
