### ISSUE TITLE
Pixi 5 with Spine 3.7, 3.8 and 4.0

### ISSUE THREAD

**Issue by goldenratio** [pixijs/spine#516]
Hey guys,
We are adding support for Spine 3.7, 3.8 and 4.0 in pixi 5. Can we open PR to pixi 5 branch? So that, more eyes sees the code?

**Comment by goldenratio** [comment]
> its just Typings that are different

That's the pain point we wanna avoid. As we have large catalogue of games.

Thanks, closing this for now.

**Comment by ivanpopelyshev** [comment]
I recently backported pixi-picture from v7 to v5 and didnt have problems with tooling. Shoudl work with v5, the only thing you have to take from v6 is old loader (instead of new Assets)
