### ISSUE TITLE
Loading spine with large texture cause runtime error.

### ISSUE THREAD

**Issue by chlind** [pixijs/spine#521]
Texture Error: frame does not fit inside the base Texture dimensions: X: 2 + 2114 = 2116 > 2048 and Y: 1362 + 2114 = 3476 > 2048

**Comment by miltoncandelero** [comment]
Your atlas and PNG file don't match. Your atlas file describes a rectangle outside of the png bounds

**Comment by chlind** [comment]
Ahh... The artist provide wrong size of texture. Thanks.
